### ISSUE TITLE
Deno "dial" API changed

### ISSUE THREAD

**Issue by stephdin** [manyuanrong/deno-smtp#1]
The API for `Deno.dail` has changed (https://github.com/denoland/deno/pull/3000)
According to https://deno.land/typedoc/interfaces/deno.dialoptions.html there is now a `DialOptions` object.

```
// smtp.ts:20:41
this._conn = await Deno.dial({
    hostname: config.host,
    port: config.port,
    transport: "tcp"
});
```

i can open a PR if you want :)

**Comment by manyuanrong** [comment]
Of course, but I hope to change the READE.md and CI configuration together

**Comment by omarhoro** [comment]
@manyuanrong greeting. Are you planning to update your package, because it is not usable for now, unfortunately

**Comment by manyuanrong** [comment]
Closed by: https://github.com/manyuanrong/deno-smtp/releases/tag/v0.4.0
