### ISSUE TITLE
README example is not runnable

### ISSUE THREAD

**Issue by tufeiping** [manyuanrong/deno-smtp#11]
await client.connect({
  host: "smtp.163.com", // ==> hostname: "smtp.163.com"
  port: 25,
  username: "username",
  password: "password",
});

// ConnectConfig define 
export interface ConnectConfig {
  hostname: string;
  port?: number;
  username: string;
  password: string;
}

**Comment by manyuanrong** [comment]
Have more error details?

**Comment by khflab** [comment]
The example tells for us to use 'host', but the Interface expects 'hostname'
