### ISSUE TITLE
Cannot use authentification

### ISSUE THREAD

**Issue by RomainCscnLF** [manyuanrong/deno-smtp#13]
Hello,

I got this error when trying to connect.

```javascript
error: TS2345 [ERROR]: Argument of type
'{ hostname: string; port: number; username: string; password: string; }' 
is not assignable to parameter of type 'ConnectConfig'.

Object literal may only specify known properties, and 'username' does not exist in type 'ConnectConfig'.
```

 I'm using this version:
```javascript
import { SmtpClient } from "https://deno.land/x/smtp@master/mod.ts";
```
as I saw that some fixed where added. I think what we're missing is the export of the connect config with authentification.

**Comment by khflab** [comment]
I'm getting the same error

**Comment by khflab** [comment]
@cbioley I think it's because your last commit splited the config interface

**Comment by cbioley** [comment]
Sorry guys, your are right. It was my first day using Deno, so I totally missed the `mod.ts` file 🙄

**Comment by cbioley** [comment]
Maybe it would be better to create an `UnauthenticatedConnectConfig` and let the `ConnectConfig` as is (no breaking changes).

Or they may probably better ways to handle it :)

**Comment by khflab** [comment]
You could do something like that on smtp.ts

> async connect(config: ConnectConfig|ConnectConfigWithAuthentication) {

```
  async connect(config: ConnectConfig|ConnectConfigWithAuthentication) {
    const conn = await Deno.connect({
      hostname: config.hostname,
      port: config.port || 25,
    });
    await this._connect(conn, config);
  }
```
