### ISSUE TITLE
Please add a release tag with the updates

### ISSUE THREAD

**Issue by Soremwar** [manyuanrong/deno-smtp#30]
@manyuanrong Deno's registry doesn't allow commit or branch imports anymore (good decision in my opinion). So in order to import from deno.land/x you have to create a version tag/release so we can use it.

To register in the new repository, just follow the instructions in the https://deno.land/x/ landing page, from there on now the process should be automated.

For everyone else, in the meantime you can import from github directly (thanks ECMA for ES modules).

Latest commit as of 03/08/2020
https://raw.githubusercontent.com/manyuanrong/deno-smtp/bc38e10b8fd683f2bca350f2885f64553ab0ea51/mod.ts

```javascript
import {
  SmtpClient
} from "https://raw.githubusercontent.com/manyuanrong/deno-smtp/bc38e10b8fd683f2bca350f2885f64553ab0ea51/mod.ts";
```

**Comment by manyuanrong** [comment]
thanks for your reminder
