### ISSUE TITLE
How to Attach PDF?

### ISSUE THREAD

**Issue by suchislife801** [manyuanrong/deno-smtp#31]
Hello. First I wanted to say this library is great and working with the latest version of Deno 1.2.3.

I would like to know if you can post an example of **how to attach PDF files to the email** message using deno?

Thank you!

**Comment by suchislife801** [comment]
Due to the utter lack of replies, I have extracted what I needed from your code and created a new version that does this.

**Comment by BayoKwendo** [comment]
Please share
