### ISSUE TITLE
Error for Deno v1.4.0

### ISSUE THREAD

**Issue by BookShell527** [manyuanrong/deno-smtp#34]
Like the other package when i updated it to Deno v1.4.0, i got error like this
```
TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import {
^
    at https://deno.land/x/smtp@v0.5.1/smtp.ts:2:1

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    ConnectConfig,
    ~~~~~~~~~~~~~
    at https://deno.land/x/smtp@v0.5.1/mod.ts:2:5

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    ConnectConfigWithAuthentication,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/smtp@v0.5.1/mod.ts:3:5

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    SendConfig,
    ~~~~~~~~~~
    at https://deno.land/x/smtp@v0.5.1/mod.ts:4:5
```
Please fix this by adding Import type and Export type for interface or any other type

**Comment by suchislife801** [comment]
Yes. Change @v0.5.1 in ALL your script imports to @v0.6.8 which is the current version of std library for deno version 1.4

**Comment by BookShell527** [comment]
I'm trying to download it, but version 0.6.8 is not released yet

**Comment by suchislife801** [comment]
The developer for this project is never around. It blows.

**Comment by Schoude** [comment]
trying to update to Deno 1.4.x now two weeks after it's release and this error is still present.
I was intentionally waiting to update Deno to avoid such issues, but I guess two weeks are not long enough. :P
this is the only dependency that causes problems updating to Deno 1.4.2 for me now.

**Comment by mooxl** [comment]
The module got finally bumped to 1.4.4 👍

**Comment by BookShell527** [comment]
I close this issue because the module already get bumped to 1.4.4
