### ISSUE TITLE
Deno 1.13 error

### ISSUE THREAD

**Issue by MichailVestnik** [manyuanrong/deno-smtp#48]
Hi! 

I use your example and get an error. It wasn't there in earlier versions...

![Снимок экрана от 2021-08-15 12-06-47](https://user-images.githubusercontent.com/87961969/129465844-8a1e325e-5782-4e59-8b63-6adc0a63190a.png)

**Comment by Schoude** [comment]
same here. probably just needs a dependency bump of the std library.

**Comment by somebody1234** [comment]
seems like it's implemented but they didn't release a new version? :(

**Comment by somebody1234** [comment]
as a stopgap solution you could use https://raw.githubusercontent.com/manyuanrong/deno-smtp/master/smtp.ts as a dependency i guess.
