### ISSUE TITLE
Coudn't understand how to use reading Readme file

### ISSUE THREAD

**Issue by omarhoro** [manyuanrong/deno-smtp#8]
Dear , author.

First of all, I want to thank you for last upgrading of your package.

Could I ask you to provide a sample example of how to use correctly your package with gmail service, because I ve got an error like:
Socket Error 10061 Connection Refused.

Feel free to close this issue.

**Comment by omarhoro** [comment]
I also tried with another mail providers. The same error @manyuanrong :

No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by manyuanrong** [comment]
@omarhoro I do n’t know where you use it, but as far as I know, there are many CI and CD platforms that prohibit SMTP, such as travis, etc., but I can send it on github actions.

**Comment by omarhoro** [comment]
I tried to use it with outlook and gmail, and I failed. 
Get smth like:
Uncaught InvalidData: received corrupt message

**Comment by omarhoro** [comment]
Maybe I can ask you to make some manual or video guide of how to use your useful package on test gmail account?

**Comment by manyuanrong** [comment]
Maybe you can find some inspiration in the test.ts file. And your suggestion is very good. I will take the time to write an article to describe the use example

**Comment by omarhoro** [comment]
@manyanrong thanks for replying. Will wait for your updated description.

**Comment by omarhoro** [comment]
@manyuanrong by the way, do we need some pre-actions or configurations?

**Comment by manyuanrong** [comment]
@omarhoro Because my gmail is only used to receive mail, I have not used it to send. I went to see it and found that gmail uses port 578 (STARTTLS protocol). Since Deno does not currently have an API similar to startTLS, there is no way. I am trying to promote the implementation of this API. Before that, I suggest you look for mail services using port 25 or port 465.

https://github.com/denoland/deno/pull/4773

**Comment by manyuanrong** [comment]
My mistake, I didn't see gmail telling me that 465 can be used, but I tried it and it did.

**Comment by manyuanrong** [comment]
I added Gmail sending configuration in Readme.md

**Comment by omarhoro** [comment]
@manyuanrong thanks for updating. I tried for 10 times, and googled. I am failed :( Could I ask you to make simple video?

**Comment by manyuanrong** [comment]
Can you give more error details？
